### ISSUE TITLE
jspp moving forward

### ISSUE THREAD

**Issue by etcimon** [rogerpoon/jspp#32] opened 2015-03-12 04:25 UTC
I stumbled on a blog post from 2014 about this project, I read the website material expecting a download link but can't find anything except a link towards installation instructions in tutorials and I got a 404 not found error. The project claims to support type safety on top of javascript without breaking existing code, so I'm curious to try it out. You seem to have the entire thing pretty much complete.

So I think the issue is that you're missing some instructions on getting started and running an example - something that runs backbone or jquery. Could you point me in a direction that doesn't involve a N/A timeline for setting it up?

**Comment by rogerpoon** [comment] 2015-03-16 20:07
It's not released. Closing because this is not a bug.

**Closed by rogerpoon** 2015-03-16 20:07 UTC

**Comment by etcimon** [comment] 2015-03-16 20:13
Thx!
